### ISSUE TITLE
Add TemplateStringCell: Allow to mix dynamic values (variables) with static values in the same cell. 

### ISSUE THREAD

**Issue by jacekkoziol** [Siemienik/XToolSet#152]
Currently there is not possible to have variable and the static text/value in the same cell, since it's not rendered correctly, so it forces to parse view model data before it's passed to the renderer.
My proposal to solve that problem is to allow to add the variables in mustache notation, like : `Some static value: {{variableValue}}`.
For the performance reasons to indicate that specific cell contains variable to replace and to keep backward compatibility, the cell could start with `#?` like: `#? Some static value: {{variableValue}}`.

**Comment by Siemienik** [comment]
Thank you for the proposal:) I've added it into proposal index. For now, I close this issue (following the workflow for proposals), and I will be open when it becomes to be accepted.

I have two more ideas for the syntax, so in assumptions:

1. Recognized because it starts by: `
 ```
## `Some static value: ${variableValue}`
```

2. if more arguments were passed into VariableCell, the last one will be a template.
```
## variableValue otherVariableValue `Some static values: {0} and {1}`
```

3. (As @jacekkoziol proposed), by adding `#?` prefix
```
#? Some static value: {{variableValue}}
```

More syntax proposals are welcome if anyone wants to share :)

**Comment by Siemienik** [comment]
I'm going to add `TemplateStringCell` regognized by using 

```
#` [TEMPLATE_STRING]
```

The solutions for string interpolation is described in #158
